apps:
  - name: IDEA
    scheme: http
    port: 8082
    # Working directory
    working-directory: /home/coder
    # File path to icon used in application launcher
    icon-path: /opt/idea/bin/idea.png
    # VNC server will be started by default in this image
    command: "/opt/idea/bin/idea.sh"
    # Array of arguments for command
    args: []
    health-check:
      http:
        scheme: "http"
        path: "/"
        port: 8082